name: mixbench
title: Mixbench
license: GPL-2.0
version: 597b7002b9
summary: A GPU benchmark tool for evaluating GPUs and CPUs
description: |
  The purpose of this benchmark tool is to evaluate performance bounds of GPUs
  (or CPUs) on mixed operational intensity kernels. The executed kernel is
  customized on a range of different operational intensity values. Modern GPUs
  are able to hide memory latency by switching execution to threads able to
  perform compute operations. Using this tool one can assess the practical
  optimum balance in both types of operations for a compute device. CUDA, HIP,
  OpenCL and SYCL implementations have been developed, targeting GPUs, or
  OpenMP when using a CPU as a target.

website: https://github.com/ekondis/mixbench
contact: https://github.com/pedro-avalos/mixbench/issues
issues: https://github.com/pedro-avalos/mixbench/issues
source-code: https://github.com/ekondis/mixbench

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  cpu:
    command: bin/mixbench-cpu
    plugs:
      - opengl
      - network-bind
      - hardware-observe
  cuda:
    command: bin/mixbench-cuda
    plugs:
      - opengl
      - network-bind
      - hardware-observe
  hip:
    command: bin/mixbench-hip
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/rocm-6.2.2/lib:$LD_LIBRARY_PATH
    plugs:
      - opengl
      - network-bind
      - hardware-observe
  ocl:
    command: bin/mixbench-ocl
    plugs:
      - opengl
      - network-bind
      - hardware-observe

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
    priority: 600
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/amdgpu/6.2.2/ubuntu
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/rocm/apt/6.2.2
    priority: 600

parts:
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  mixbench:
    after: [glib-only]
    plugin: cmake
    source: https://github.com/ekondis/mixbench.git
    source-type: git
    source-commit: 597b7002b9596685e2911acaf13c6780a06e7286
    build-snaps: [cmake]
    build-packages:
      - cuda-toolkit
      - rocm
      - hip-dev
      - rocm-hip-runtime-dev
    stage-packages:
      - libgomp1
      - libnuma1
      - hip-runtime-amd
      - hsa-rocr
      - rocprofiler-register
      - ocl-icd-libopencl1
      - libglu1-mesa
    build-environment:
      - CUDACXX: /usr/local/cuda/bin/nvcc
      - HIP_PATH: /opt/rocm
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      mkdir -p $CRAFT_PART_INSTALL/bin

      mkdir -p build-cpu
      cd build-cpu
      cmake ../mixbench-cpu
      cmake --build .
      cp mixbench-cpu $CRAFT_PART_INSTALL/bin
      cd ..

      mkdir -p build-cuda
      cd build-cuda
      cmake ../mixbench-cuda -DCMAKE_CUDA_ARCHITECTURES=all
      cmake --build .
      cp mixbench-cuda $CRAFT_PART_INSTALL/bin/
      cd ..

      mkdir -p build-hip
      cd build-hip
      cmake ../mixbench-hip
      cmake --build .
      cp mixbench-hip $CRAFT_PART_INSTALL/bin/
      cd ..

      mkdir -p build-opencl
      cd build-opencl
      cmake ../mixbench-opencl
      cmake --build .
      cp mixbench-ocl $CRAFT_PART_INSTALL/bin/
      cd ..
    stage:
      - -opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so*
      - -opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so*
      - -opt/rocm-6.2.2/lib/libhiprtc.so*
      - -opt/rocm-6.2.2/lib/librocm-core.so*
      - -usr/lib/x86_64-linux-gnu/libform.so*
      - -usr/lib/x86_64-linux-gnu/libmenu.so*
      - -usr/lib/x86_64-linux-gnu/libpanel.so*
      - -usr/lib/x86_64-linux-gnu/libncurses.so*
